.PHONY: up down logs migrate seed test fmt

up:            ## Start the whole stack
	docker compose up --build

down:          ## Stop and remove containers
	docker compose down

logs:          ## Tail logs
	docker compose logs -f

migrate:       ## Run DB migrations inside the api container
	docker compose exec api alembic upgrade head

seed:          ## Load demo tickets
	docker compose exec api python -m scripts.seed

test:          ## Run the test suite (needs deps installed locally)
	pytest

revision:      ## Create a new autogenerated migration: make revision m="msg"
	docker compose exec api alembic revision --autogenerate -m "$(m)"
